In [1]:
import pandas as pd

In [2]:
s= pd.Series([1,2,3,4,5])

In [3]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
s= pd.Series([1,2,3,4,5] , index = ['a','b','c','d','e'])

In [5]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [7]:
df = pd.DataFrame({ "name": ["ashu","harshal","shubham"] , "marks" :[99,90,89]})

In [8]:
df

      name  marks
0     ashu     99
1  harshal     90
2  shubham     89

In [10]:
import numpy as np
arr =  np.array([[1,2,3] , [4,5,6]])

In [11]:
df = pd.DataFrame(arr , columns = ["c1","c2","c3"] , index = ['a' , 'b'])

In [12]:
df

   c1  c2  c3
a   1   2   3
b   4   5   6

In [13]:
df =  pd.read_csv("student.csv")

In [14]:
df

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [15]:
df.head(10)

   id         name  class  mark  gender
0   1     John Deo   Four    75  female
1   2     Max Ruin  Three    85    male
2   3       Arnold  Three    55    male
3   4   Krish Star   Four    60  female
4   5    John Mike   Four    60  female
5   6    Alex John   Four    55    male
6   7  My John Rob  Fifth    78    male
7   8       Asruid   Five    85    male
8   9      Tes Qry    Six    78    male
9  10     Big John   Four    55  female

In [16]:
df.tail(10)

    id         name  class  mark  gender
25  26       Crelea  Seven    79    male
26  27     Big Nose  Three    81  female
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [17]:
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    35 non-null     object
 2   class   35 non-null     object
 3   mark    35 non-null     int64
 4   gender  35 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [19]:
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26       Big Nose
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [20]:
df.iloc[4]

id                5
name      John Mike
class          Four
mark             60
gender       female
Name: 4, dtype: object

In [21]:
df2 = pd.read_csv("StudwithNAN.csv")

In [22]:
df2

    id         name  class  mark  gender
0    1     John Deo   Four  75.0  female
1    2     Max Ruin  Three  85.0    male
2    3       Arnold    NaN  55.0    male
3    4   Krish Star   Four  60.0  female
4    5    John Mike   Four  60.0  female
5    6    Alex John   Four  55.0    male
6    7  My John Rob    NaN  78.0    male
7    8       Asruid   Five  85.0     NaN
8    9      Tes Qry    Six  78.0    male
9   10     Big John   Four  55.0  female
10  11       Ronald    Six  89.0  female
11  12        Recky    Six  94.0  female
12  13          Kty    NaN  88.0  female
13  14         Bigy  Seven   NaN  female
14  15     Tade Row   Four  88.0    male
15  16        Gimmy   Four  88.0    male
16  17        Tumyu    Six  54.0    male
17  18        Honny   Five  75.0     NaN
18  19        Tinny   Nine  18.0    male
19  20       Jackly   Nine  65.0  female
20  21          NaN   Four  69.0  female
21  22       Reggid  Seven  55.0  female
22  23        Herod  Eight  79.0    male
23  24    Tiddy Now  Seven  78.0    male
24  25     Giff Tow  Seven  88.0    male
25  26       Crelea  Seven  79.0    male
26  27     Big Nose  Three  81.0     NaN
27  28    Rojj Base  Seven  86.0  female
28  29  Tess Played  Seven  55.0    male
29  30    Reppy Red    Six  79.0  female
30  31  Marry Toeey   Four  88.0    male
31  32    Binn Rott  Seven  90.0  female
32  33    Kenn Rein    NaN  96.0  female
33  34     Gain Toe  Seven  69.0    male
34  35   Rows Noump    Six  88.0  female

In [23]:
df2.dropna()

    id         name  class  mark  gender
0    1     John Deo   Four  75.0  female
1    2     Max Ruin  Three  85.0    male
3    4   Krish Star   Four  60.0  female
4    5    John Mike   Four  60.0  female
5    6    Alex John   Four  55.0    male
8    9      Tes Qry    Six  78.0    male
9   10     Big John   Four  55.0  female
10  11       Ronald    Six  89.0  female
11  12        Recky    Six  94.0  female
14  15     Tade Row   Four  88.0    male
15  16        Gimmy   Four  88.0    male
16  17        Tumyu    Six  54.0    male
18  19        Tinny   Nine  18.0    male
19  20       Jackly   Nine  65.0  female
21  22       Reggid  Seven  55.0  female
22  23        Herod  Eight  79.0    male
23  24    Tiddy Now  Seven  78.0    male
24  25     Giff Tow  Seven  88.0    male
25  26       Crelea  Seven  79.0    male
27  28    Rojj Base  Seven  86.0  female
28  29  Tess Played  Seven  55.0    male
29  30    Reppy Red    Six  79.0  female
30  31  Marry Toeey   Four  88.0    male
31  32    Binn Rott  Seven  90.0  female
33  34     Gain Toe  Seven  69.0    male
34  35   Rows Noump    Six  88.0  female

In [25]:
df2.fillna("nothing here")

    id          name         class          mark        gender
0    1      John Deo          Four          75.0        female
1    2      Max Ruin         Three          85.0          male
2    3        Arnold  nothing here          55.0          male
3    4    Krish Star          Four          60.0        female
4    5     John Mike          Four          60.0        female
5    6     Alex John          Four          55.0          male
6    7   My John Rob  nothing here          78.0          male
7    8        Asruid          Five          85.0  nothing here
8    9       Tes Qry           Six          78.0          male
9   10      Big John          Four          55.0        female
10  11        Ronald           Six          89.0        female
11  12         Recky           Six          94.0        female
12  13           Kty  nothing here          88.0        female
13  14          Bigy         Seven  nothing here        female
14  15      Tade Row          Four          88.0          male
15  16         Gimmy          Four          88.0          male
16  17         Tumyu           Six          54.0          male
17  18         Honny          Five          75.0  nothing here
18  19         Tinny          Nine          18.0          male
19  20        Jackly          Nine          65.0        female
20  21  nothing here          Four          69.0        female
21  22        Reggid         Seven          55.0        female
22  23         Herod         Eight          79.0          male
23  24     Tiddy Now         Seven          78.0          male
24  25      Giff Tow         Seven          88.0          male
25  26        Crelea         Seven          79.0          male
26  27      Big Nose         Three          81.0  nothing here
27  28     Rojj Base         Seven          86.0        female
28  29   Tess Played         Seven          55.0          male
29  30     Reppy Red           Six          79.0        female
30  31   Marry Toeey          Four          88.0          male
31  32     Binn Rott         Seven          90.0        female
32  33     Kenn Rein  nothing here          96.0        female
33  34      Gain Toe         Seven          69.0          male
34  35    Rows Noump           Six          88.0        female

In [28]:
df2.rename(columns={"name":"Name"})

    id         Name  class  mark  gender
0    1     John Deo   Four  75.0  female
1    2     Max Ruin  Three  85.0    male
2    3       Arnold    NaN  55.0    male
3    4   Krish Star   Four  60.0  female
4    5    John Mike   Four  60.0  female
5    6    Alex John   Four  55.0    male
6    7  My John Rob    NaN  78.0    male
7    8       Asruid   Five  85.0     NaN
8    9      Tes Qry    Six  78.0    male
9   10     Big John   Four  55.0  female
10  11       Ronald    Six  89.0  female
11  12        Recky    Six  94.0  female
12  13          Kty    NaN  88.0  female
13  14         Bigy  Seven   NaN  female
14  15     Tade Row   Four  88.0    male
15  16        Gimmy   Four  88.0    male
16  17        Tumyu    Six  54.0    male
17  18        Honny   Five  75.0     NaN
18  19        Tinny   Nine  18.0    male
19  20       Jackly   Nine  65.0  female
20  21          NaN   Four  69.0  female
21  22       Reggid  Seven  55.0  female
22  23        Herod  Eight  79.0    male
23  24    Tiddy Now  Seven  78.0    male
24  25     Giff Tow  Seven  88.0    male
25  26       Crelea  Seven  79.0    male
26  27     Big Nose  Three  81.0     NaN
27  28    Rojj Base  Seven  86.0  female
28  29  Tess Played  Seven  55.0    male
29  30    Reppy Red    Six  79.0  female
30  31  Marry Toeey   Four  88.0    male
31  32    Binn Rott  Seven  90.0  female
32  33    Kenn Rein    NaN  96.0  female
33  34     Gain Toe  Seven  69.0    male
34  35   Rows Noump    Six  88.0  female

In [29]:
df2

    id         name  class  mark  gender
0    1     John Deo   Four  75.0  female
1    2     Max Ruin  Three  85.0    male
2    3       Arnold    NaN  55.0    male
3    4   Krish Star   Four  60.0  female
4    5    John Mike   Four  60.0  female
5    6    Alex John   Four  55.0    male
6    7  My John Rob    NaN  78.0    male
7    8       Asruid   Five  85.0     NaN
8    9      Tes Qry    Six  78.0    male
9   10     Big John   Four  55.0  female
10  11       Ronald    Six  89.0  female
11  12        Recky    Six  94.0  female
12  13          Kty    NaN  88.0  female
13  14         Bigy  Seven   NaN  female
14  15     Tade Row   Four  88.0    male
15  16        Gimmy   Four  88.0    male
16  17        Tumyu    Six  54.0    male
17  18        Honny   Five  75.0     NaN
18  19        Tinny   Nine  18.0    male
19  20       Jackly   Nine  65.0  female
20  21          NaN   Four  69.0  female
21  22       Reggid  Seven  55.0  female
22  23        Herod  Eight  79.0    male
23  24    Tiddy Now  Seven  78.0    male
24  25     Giff Tow  Seven  88.0    male
25  26       Crelea  Seven  79.0    male
26  27     Big Nose  Three  81.0     NaN
27  28    Rojj Base  Seven  86.0  female
28  29  Tess Played  Seven  55.0    male
29  30    Reppy Red    Six  79.0  female
30  31  Marry Toeey   Four  88.0    male
31  32    Binn Rott  Seven  90.0  female
32  33    Kenn Rein    NaN  96.0  female
33  34     Gain Toe  Seven  69.0    male
34  35   Rows Noump    Six  88.0  female

In [30]:
df2.rename(columns={"name":"Name"} , inplace = True)

In [31]:
df2

    id         Name  class  mark  gender
0    1     John Deo   Four  75.0  female
1    2     Max Ruin  Three  85.0    male
2    3       Arnold    NaN  55.0    male
3    4   Krish Star   Four  60.0  female
4    5    John Mike   Four  60.0  female
5    6    Alex John   Four  55.0    male
6    7  My John Rob    NaN  78.0    male
7    8       Asruid   Five  85.0     NaN
8    9      Tes Qry    Six  78.0    male
9   10     Big John   Four  55.0  female
10  11       Ronald    Six  89.0  female
11  12        Recky    Six  94.0  female
12  13          Kty    NaN  88.0  female
13  14         Bigy  Seven   NaN  female
14  15     Tade Row   Four  88.0    male
15  16        Gimmy   Four  88.0    male
16  17        Tumyu    Six  54.0    male
17  18        Honny   Five  75.0     NaN
18  19        Tinny   Nine  18.0    male
19  20       Jackly   Nine  65.0  female
20  21          NaN   Four  69.0  female
21  22       Reggid  Seven  55.0  female
22  23        Herod  Eight  79.0    male
23  24    Tiddy Now  Seven  78.0    male
24  25     Giff Tow  Seven  88.0    male
25  26       Crelea  Seven  79.0    male
26  27     Big Nose  Three  81.0     NaN
27  28    Rojj Base  Seven  86.0  female
28  29  Tess Played  Seven  55.0    male
29  30    Reppy Red    Six  79.0  female
30  31  Marry Toeey   Four  88.0    male
31  32    Binn Rott  Seven  90.0  female
32  33    Kenn Rein    NaN  96.0  female
33  34     Gain Toe  Seven  69.0    male
34  35   Rows Noump    Six  88.0  female